# Generated by Django 4.0.3 on 2022-03-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('department', models.CharField(default='', max_length=60)),
                ('tags', models.CharField(default='', max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='Projects/')),
            ],
        ),
    ]
