# Generated by Django 4.0.3 on 2022-03-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_institue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
