# Generated by Django 4.0.3 on 2022-03-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0003_delete_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=250)),
                ('department', models.CharField(default='', max_length=60)),
                ('tags', models.CharField(default='', max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='Projects/')),
            ],
        ),
    ]
