# Generated by Django 4.0.3 on 2022-03-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0004_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
