# Generated by Django 4.0.3 on 2022-03-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0006_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='institue',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='institue',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='institue',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
    ]
