# Generated by Django 4.0.3 on 2022-03-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0007_institue_city_institue_country_institue_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='institue',
            name='otp',
            field=models.CharField(default='', max_length=10),
        ),
    ]
