# Generated by Django 4.0.3 on 2022-03-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0008_institue_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='institue',
            name='otpverified',
            field=models.BooleanField(default=False),
        ),
    ]
